### ISSUE TITLE
suggestion: remove async block from constructor

### ISSUE THREAD

**Issue by micalevisk** [jotterkain/e-commerce#1]
https://github.com/jotterkain/e-commerce/blob/6118f163563f4c4acbc724fb0ba21901e9019fb6/src/security/security.service.ts#L11-L25

Instead of having the above async flow on `constructor`, you could use one nestjs [lifecycle hook](https://docs.nestjs.com/fundamentals/lifecycle-events#lifecycle-events-1) like this:

```ts
async onModuleInit() {
  try { 
     const password = this.config.get<string>('ENCRYPT_PASSWORD'); 
     this.iv = Buffer.from(this.config.get<String>('ENCRYPT_IV'), 'base64'); 
     this.key = await promisify(scrypt)(password, 'salt', 32) as Buffer; 
   } catch (err) { 
     console.error(err); 
   } 
}
```

**Comment by jotterkain** [comment]
Thank you very much sir, it worked like a charm. I'll definitely learn more about `lifecycle hook` in NestJs Apps
